[env:esp32c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
lib_deps =
  zinggJM/GxEPD2@^1.5.2
  olikraus/U8g2@^2.36.2
  olikraus/U8g2_for_Adafruit_GFX@^1.8.0
extra_scripts = pre:tools/prepare_book.py
